export enum EnvironmentKeys {
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',
  DB_SYNC = 'DB_SYNC',
  SCRAPER_PARALEL_JOBS = 'SCRAPER_PARALEL_JOBS',
}
